adapters: [emotion, intent, kws, langid, speaker_ver, asr, vocalsound]
method: ties
merge_mode: common
method_params:
  k: 20
  lambda: 1.0
split: test
eval_tasks: [emotion, intent, kws, langid, speaker_ver, asr, vocalsound, speech_qa]
save_merged: false
